### ISSUE TITLE
Student Creation

### ISSUE THREAD

**Issue by Sharaf-Mansour** [Sharaf-Mansour/PreMaster-GP#46]
## Task
Students Data should be separated in Different Database because it will heavily store Static files
Along its tables will be accusable in specific times (Students have a limited time to sign up) 
Also sensitive data will be stored so can not risk it being in same place is the collage data
Stored data (For now) are

- Student ID* (GUID)
- Name Arabic* (String) 
- Name English* (String)
- Is Foreigner*  (Boolean)
-  Nationality* (String)
- NID* (String)
  - Only 14
  - Numbers only
  - Only Required if Egyptian
- Passport* (String)
  - Only Required If not Egyptian
- Birthday* (DateTime)
- Place Of Birth* (String)
- Sex* (Boolean)
- Place Of Residence* (String)
- Job (String)
- Company (String)
- Phone* (String)
  - Max 15
  - Numbers format Only 
- Email* (String) 
   - Mail format only
- Last Qualification* (String)
- Collage* (String)
- University* (String)
- Grade* (String)
- [x] Apply Academic Degree** (LookUp) 
- [x] Apply Specialization** (LookUp) 
- Apply Date (DateTime)
- [x] Apply Status (LookUp)
- Student Img (String) Base 64
- Student Qual Img (String) Base 64
- Student SSN Img (String) Base 64
- Student Birth Cert Img (String) Base 64
## Work needed
Create Database for both archive and Creation
Create Student Table
Create Student Account Table
Create Look Ups For Academic Degree and Specialization 
Create brokers and Service
Create Orchestration 
(Optional) Create Unit test for Student Creation
 ## Next Step
Validations
API integration

**Comment by Sharaf-Mansour** [comment]
## Idea
Apply ID is the numeric value of Apply Date

**Comment by Sharaf-Mansour** [comment]
## Task for today

- [ ]  Create Stored Proc to fill the Look ups
- [ ]  Create Stored Proc for student (CRUD)
- [ ]  Create the API

**Comment by Sharaf-Mansour** [comment]
## Task for today

- [x] Create Stored Proc to get (Accepted - Rejected - Pending - All) Student List
- [x] Create Student Creation Broker
- [ ] Create Student Creation Service
